echo Running OCaml code...
ocaml $1.ml $2 >$1.s
# Exclude C stdlib and include SDIV and UDIV instructions
echo Compiling generated assembly...
gcc -nostdlib -mcpu=cortex-a72 -mtune=cortex-a72 -mfpu=neon-fp-armv8 $1.s -o $1
echo Running executable...
./$1
echo $?
